# Generated by Django 4.1.4 on 2024-01-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joyboy_app.post_category'),
            preserve_default=False,
        ),
    ]
