# Generated by Django 4.1.4 on 2024-01-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0002_posts_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_category',
            new_name='post_category_id',
        ),
    ]
