# Generated by Django 4.1.4 on 2024-01-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0003_rename_post_category_posts_post_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_category_id',
            new_name='post_category',
        ),
    ]
