# Generated by Django 4.1.4 on 2024-01-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adress',
            new_name='address',
        ),
    ]
