# Generated by Django 4.1.4 on 2024-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0006_rename_adress_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Service_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='service_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
