# Generated by Django 4.1.4 on 2024-01-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0007_booking_service_id_booking_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Service_id',
            new_name='service_id',
        ),
    ]
