# Generated by Django 4.1.4 on 2024-01-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0009_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
