# Generated by Django 4.1.4 on 2024-01-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0011_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.ImageField(default=0, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
