# Generated by Django 4.1.4 on 2024-02-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0012_register_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
