# Generated by Django 3.2.8 on 2024-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0015_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
