# Generated by Django 3.2.8 on 2024-02-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0019_turf_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='photo',
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='turf_photos/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='joyboy_app.turf')),
            ],
        ),
    ]
