# Generated by Django 3.2.8 on 2024-02-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0020_auto_20240220_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='turf_photos/'),
        ),
        migrations.DeleteModel(
            name='TurfImage',
        ),
    ]
