# Generated by Django 3.2.8 on 2024-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyboy_app', '0021_auto_20240221_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
